version: '3'

services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile-flask
    ports:
      - "5000:80"
    depends_on:
      - redis
      - mongo
      
  redis:
    image: "redis:latest"

  mongo:
    image: "mongo:latest"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
